- app/views/layouts/application.html.erb
> asset bug fixed

- app/controllers/friends_controller.rb
Made the basic controller for friends
> made index and show, have commented in new and create for later

- config/routes.rb
> pages#home root added plus routes for friends index show new create

- Gemfile
- Gemfile.lock
- app/controllers/friends_controller.rb
- app/models/friend.rb
- db/seeds.rb
> seed file filled, merge for testing

- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/views/friends/index.html.erb
- db/seeds.rb
> Index view

- db/seeds.rb
1  decimal place becomes 2 decimals
> seed price changed

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
- db/seeds.rb
> Changed logo

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/friends/_show.scss
- app/views/friends/show.html.erb
> updated show-html-view css

- app/assets/stylesheets/friends/_show.scss
- app/views/friends/show.html.erb
- config/routes.rb
Updated the friend-show-routing, friend-show-css and routes.rb
> updated the friend-show-routing, friend-show-css  and routes.rb

- app/assets/stylesheets/friends/_show.scss
- app/controllers/friends_controller.rb
- app/models/booking.rb
- app/views/friends/show.html.erb
Updated friend-show-page-booking-form
> updated friend-show-page-booking-form

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/bookings/_new.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_friends-index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/bookings/new.html.erb
- app/views/friends/index.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
updated navbar-css friend-index-css created bookings-new-page
> updated navbar-css friend-index-css created bookings-new-page

- app/views/layouts/application.html.erb
> log out error bug fix

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/friends/_show.scss
- app/controllers/friends_controller.rb
- app/models/friend.rb
- app/views/friends/index.html.erb
- app/views/friends/new.html.erb
- app/views/friends/show.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220831150825_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
Added images to seed and the cloudinary config setup,
> Add cloudinary images

- app/views/friends/index.html.erb
- config/environments/development.rb
- db/seeds.rb
Styling changes, but will need to remove the development change when using to heroic
>  capital names, changed displayed address and position on page

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/friends/_show.scss
- app/javascript/controllers/day_counter.js
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/friends/new.html.erb
- app/views/friends/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
> Update bookings journey

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_friends-index.scss
- app/views/friends/index.html.erb
> card fliping

- app/controllers/bookings_controller.rb
- app/javascript/controllers/day_counter.js
- app/javascript/controllers/day_counter_controller.js
- app/javascript/controllers/hello_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/views/friends/show.html.erb
- package.json
- yarn.lock
finished booking-form price calculation
> Update booking form

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/friends/_show.scss
- app/views/shared/_navbar.html.erb
> search bar spaced

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/bookings/_new.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/friends/_show.scss
- app/assets/stylesheets/pages/_friends-index.scss
- app/views/bookings/confirm.html.erb
- app/views/bookings/new.html.erb
- app/views/friends/index.html.erb
- app/views/friends/new.html.erb
- app/views/friends/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
> updated css

- .gitignore
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
• Added " | lingfung's edition" to the title
• Deleted extra spacing in application.html.erb
• Deleted unused code in home.html.erb
> Home page frontend

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Reverts ljdbar/-RENT_A_FRIEND#54
> Revert "Home page frontend"
